"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {
    "includes":[
        "pynput.keyboard._darwin",
        "pynput.mouse._darwin"
    ],
    'iconfile':'icons/icon.ico',
    "plist": {
        "LSPrefersPPC": True
    }
}

setup(
    name="SDV AC",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
